export const FETCH_POSTS = 'FETCH_POSTS'
export const VOTE_POST = 'VOTE_POST'
export const CHANGE_SORT = 'CHANGE_SORT'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
